spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/xiangcuhui?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: '407454xl..'
  servlet:
    multipart:
      enabled: true
      max-file-size: 5GB
      max-request-size: 5GB
  resources:
    static-locations: file:D:/WorkSpace/VueProjects/xiangcuhui/files/
  mail:
    host: smtp.qq.com            # QQ 邮箱的 SMTP 服务器地址
    port: 587
    username: 3230144337@qq.com  # QQ邮箱地址
    password: wodmybcfrjlrdbbi  # 授申请得到的授权码，不是邮箱密码
    properties:
      mail.smtp.auth: true        # 开启 SMTP 身份验证
      mail.smtp.starttls.enable: true  # 开启 STARTTLS 加密
    default-encoding: UTF-8
  redis:
    host: localhost
    port: 6379
    password: # 如果有密码，可以配置密码
    timeout: 6000

mybatis:
  mapper-locations: classpath:mybatis/*.xml
server:
  port: 8081
ip: localhost




